-- Baseline schema, replacing Hibernate's `ddl-auto: update`. Written to be portable across the
-- two datasources this project actually runs against (H2 for tests/local dev, PostgreSQL for
-- shared multi-server deployment) - no vendor-specific syntax.
--
-- Derived by hand, column-by-column, from the JPA entities in com.firstclub.membership.domain.
-- Column names follow Spring Boot's default physical naming strategy (camelCase -> snake_case)
-- for every field with no explicit @Column(name=...); fields that DO specify one (order_value,
-- user_id, etc.) use that exact name here. NOT NULL is applied to every Java primitive field
-- (rank, versionNumber, rollingWindowDays, manualTierOverride, cancelled - primitives can never
-- be null, so Hibernate would reject a null write against these regardless of what the DDL
-- allows) and to every field with an explicit `nullable = false`. Every other column is left
-- nullable, matching its entity exactly, rather than guessed tighter - the FK/unique constraints
-- below are what the application's correctness actually depends on, not extra NOT NULLs this
-- migration doesn't have positive evidence for.
--
-- `spring.jpa.hibernate.ddl-auto` is `none` against this migration (see application.yml) rather
-- than `validate`: validate would be the stricter, more correct pairing, but doing that safely
-- requires confirming Hibernate's exact expected DDL against a live schema-export, which this
-- change was not able to do (see accompanying note). Run the full test suite after applying this
-- migration - MembershipApiIntegrationTest exercises nearly every column and constraint here,
-- so a real mismatch will surface as a test failure, not a silent drift.

CREATE TABLE app_user (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(255) NOT NULL,
    email  VARCHAR(255) NOT NULL,
    cohort VARCHAR(255),
    CONSTRAINT uk_app_user_email UNIQUE (email)
);

CREATE TABLE plan (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_type VARCHAR(255),
    price     NUMERIC(19, 2),
    currency  VARCHAR(255)
);

CREATE TABLE plan_version (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id        BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    price          NUMERIC(19, 2) NOT NULL,
    currency       VARCHAR(3) NOT NULL,
    CONSTRAINT fk_plan_version_plan FOREIGN KEY (plan_id) REFERENCES plan (id),
    CONSTRAINT uk_plan_version_plan_number UNIQUE (plan_id, version_number)
);

CREATE TABLE tier (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(255),
    rank                INTEGER NOT NULL,
    criteria_match_mode VARCHAR(255)
);

CREATE TABLE tier_criterion (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier_id             BIGINT NOT NULL,
    criteria_type       VARCHAR(255),
    window_type         VARCHAR(255),
    rolling_window_days INTEGER NOT NULL,
    threshold           NUMERIC(19, 2),
    cohort_name         VARCHAR(255),
    CONSTRAINT fk_tier_criterion_tier FOREIGN KEY (tier_id) REFERENCES tier (id)
);

CREATE TABLE tier_benefit (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier_id      BIGINT NOT NULL,
    benefit_type VARCHAR(255),
    param_value  NUMERIC(19, 2),
    scope        VARCHAR(255),
    CONSTRAINT fk_tier_benefit_tier FOREIGN KEY (tier_id) REFERENCES tier (id)
);

CREATE TABLE subscription (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT NOT NULL,
    plan_id               BIGINT NOT NULL,
    tier_id               BIGINT NOT NULL,
    plan_version_id       BIGINT NOT NULL,
    status                VARCHAR(255),
    tier_source           VARCHAR(255),
    start_date            TIMESTAMP,
    end_date              TIMESTAMP,
    manual_tier_override  BOOLEAN NOT NULL,
    version               BIGINT,
    CONSTRAINT fk_subscription_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_subscription_plan FOREIGN KEY (plan_id) REFERENCES plan (id),
    CONSTRAINT fk_subscription_tier FOREIGN KEY (tier_id) REFERENCES tier (id),
    CONSTRAINT fk_subscription_plan_version FOREIGN KEY (plan_version_id) REFERENCES plan_version (id)
);

CREATE TABLE subscription_idempotency (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    plan_id         BIGINT NOT NULL,
    tier_id         BIGINT NOT NULL,
    subscription_id BIGINT NOT NULL,
    CONSTRAINT fk_subscription_idempotency_subscription FOREIGN KEY (subscription_id) REFERENCES subscription (id),
    CONSTRAINT uk_subscription_idempotency_user_key UNIQUE (user_id, idempotency_key),
    CONSTRAINT uk_subscription_idempotency_subscription UNIQUE (subscription_id)
);

-- No FK to app_user here on purpose - ActiveMembershipLock.userId is a plain Long in the
-- entity (no @ManyToOne), so Hibernate itself never mapped a relationship for this column
-- either. Adding one here would be a constraint the entity does not actually declare.
CREATE TABLE active_membership_lock (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    subscription_id BIGINT,
    CONSTRAINT uk_active_membership_lock_user UNIQUE (user_id)
);

CREATE TABLE order_record (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    order_value NUMERIC(19, 2) NOT NULL,
    placed_at   TIMESTAMP,
    cancelled   BOOLEAN NOT NULL,
    CONSTRAINT fk_order_record_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);
