-- Adds the append-only tier-change audit trail (see TierChangeAudit). A NEW migration, not an
-- edit to V1__init_schema.sql - Flyway computes and stores a checksum per applied migration, and
-- changing an already-applied file's content breaks that checksum for anyone who already ran
-- V1 (including this project's own test suite's H2 instance across runs, and any Postgres
-- deployment that already migrated). Schema changes after the first migration always arrive as
-- a new, additively-named file.
--
-- No foreign keys here, matching V1's own stated principle for ActiveMembershipLock and
-- SubscriptionIdempotency's reference columns: TierChangeAudit's userId/subscriptionId/
-- previousTierId/newTierId are plain Longs in the entity (not @ManyToOne relations), so a DDL
-- foreign key here would be a constraint the entity mapping does not actually declare.

CREATE TABLE tier_change_audit (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    subscription_id  BIGINT NOT NULL,
    previous_tier_id BIGINT,
    new_tier_id      BIGINT NOT NULL,
    tier_source      VARCHAR(255) NOT NULL,
    changed_at       TIMESTAMP NOT NULL
);

-- Every read of this table is "give me one user's history in order" (see
-- TierChangeAuditRepository.findByUserIdOrderByChangedAtAsc) - index for exactly that.
CREATE INDEX idx_tier_change_audit_user_id ON tier_change_audit (user_id, changed_at);
